export const DISCARD_ROOM = 'DISCARD_ROOM';
export const DISCARD_ECONOMY_ROOM = 'DISCARD_ECONOMY_ROOM';
export const DISCARD_BUSINESS_ROOM = 'DISCARD_BUSINESS_ROOM';
export const DISCARD_ACTIVITY_SLOT = 'DISCARD_ACTIVITY_SLOT';
export const DISCARD_BILLIARD_SLOT = 'DISCARD_BILLIARD_SLOT';
export const DISCARD_SWIMMING_SLOT = 'DISCARD_SWIMMING_SLOT';